import type { Theme } from "./types";

export const THEMES: Record<string, Theme> = {
  pup: {
    name: "Pup Pals",
    nameHe: "כלבלבים",
    paper: "#fff8ee",
    paperDeep: "#f7ebd5",
    ink: "#3a2a1c",
    inkSoft: "#7a6248",
    accent: "#d97742",
    accent2: "#6fa8c4",
    halo: "#f5d28a",
    cardBg: "#ffffff",
    cardBorder: "#e8d8be",
    fridayAccent: "#cf6a5a",
    fontHead: '"Fredoka", system-ui, sans-serif',
    fontBody: '"Nunito", system-ui, sans-serif',
    dayTints: ["#fde7c8", "#e7eef5", "#fce4d4", "#e6e9d6", "#f4dec6", "#f0e0e9", "#dde7ee"],
    sticker: "🐾",
    motif: "paw",
    mascots: ["🐶", "🐕", "🦴"],
    decorChars: ["🐾", "🦴", "★", "♥", "✦", "🐶", "🐾", "●"],
  },
  piggy: {
    name: "Piggy Town",
    nameHe: "עיר חזרזרים",
    paper: "#fff5f7",
    paperDeep: "#fde0e8",
    ink: "#4a1d2c",
    inkSoft: "#8b5468",
    accent: "#e85a8a",
    accent2: "#7cc6e8",
    halo: "#ffc6d8",
    cardBg: "#ffffff",
    cardBorder: "#f3cdda",
    fridayAccent: "#c93e72",
    fontHead: '"Fredoka", system-ui, sans-serif',
    fontBody: '"Quicksand", system-ui, sans-serif',
    dayTints: ["#ffe1ec", "#e0f1fb", "#ffe7d4", "#e6f4dd", "#fff0c8", "#f3dff5", "#dde9f7"],
    sticker: "🌸",
    motif: "heart",
    mascots: ["🐷", "🐽", "🌸"],
    decorChars: ["🌸", "💖", "🐷", "✨", "🌷", "🦋", "♥", "✦"],
  },
  hero: {
    name: "Web Hero",
    nameHe: "גיבור הקורים",
    paper: "#1a1f3a",
    paperDeep: "#0f1428",
    ink: "#fff8f0",
    inkSoft: "#aab3d4",
    accent: "#e63a3a",
    accent2: "#3a7eff",
    halo: "#ffd166",
    cardBg: "#262d52",
    cardBorder: "#3a4378",
    fridayAccent: "#ffd166",
    fontHead: '"Bangers", "Fredoka", system-ui, sans-serif',
    fontBody: '"Nunito", system-ui, sans-serif',
    dayTints: ["#2c3563", "#273a66", "#3a2c5e", "#2c4f5e", "#5e3030", "#3d3060", "#283a4a"],
    sticker: "✦",
    motif: "web",
    mascots: ["🕷️", "🕸️", "🦸"],
    decorChars: ["🕸️", "✦", "💥", "⚡", "★", "🕷️", "✺", "●"],
  },
  explorer: {
    name: "Big Adventure",
    nameHe: "הרפתקה גדולה",
    paper: "#fffbe6",
    paperDeep: "#fff0a8",
    ink: "#1a2e5c",
    inkSoft: "#5b6a8f",
    accent: "#ff8a1f",
    accent2: "#1f7be8",
    halo: "#ffd84a",
    cardBg: "#ffffff",
    cardBorder: "#ffd84a",
    fridayAccent: "#22a96b",
    fontHead: '"Fredoka", system-ui, sans-serif',
    fontBody: '"Nunito", system-ui, sans-serif',
    dayTints: ["#ffe6a8", "#cfe6ff", "#ffd6b0", "#d6f0c8", "#ffe0a0", "#e8d8ff", "#bce0ff"],
    sticker: "★",
    motif: "star",
    mascots: ["🦊", "🧭", "⛺"],
    decorChars: ["★", "🧭", "🍃", "⛰️", "🦊", "🌟", "✦", "♥"],
  },
  sisters: {
    name: "Frost & Flame",
    nameHe: "כפור ולהבה",
    paper: "#f3f0fb",
    paperDeep: "#dce0f5",
    ink: "#1a1b3a",
    inkSoft: "#6a6f9b",
    accent: "#5fb0e8",
    accent2: "#e85535",
    halo: "#bfe4f7",
    cardBg: "#ffffff",
    cardBorder: "#cdd5ee",
    fridayAccent: "#e85535",
    fontHead: '"Fredoka", system-ui, sans-serif',
    fontBody: '"Quicksand", system-ui, sans-serif',
    dayTints: ["#e3effa", "#fde2db", "#ddeaf6", "#f6dfd6", "#e3effa", "#fde2db", "#cfe0f0"],
    sticker: "❄",
    motif: "snowflake",
    mascots: ["⛄", "🦌", "🔥"],
    decorChars: ["❄", "✦", "❅", "🦌", "⛄", "★", "♥", "🔥"],
  },
};

export const themeStyle = (t: Theme) =>
  ({
    "--paper": t.paper,
    "--paperDeep": t.paperDeep,
    "--ink": t.ink,
    "--inkSoft": t.inkSoft,
    "--accent": t.accent,
    "--accent2": t.accent2,
    "--halo": t.halo,
    "--cardBg": t.cardBg,
    "--cardBorder": t.cardBorder,
    "--fri": t.fridayAccent,
    "--fontHead": t.fontHead,
    "--fontBody": t.fontBody,
  }) as React.CSSProperties;
